#2 feature(lab2): Реализовал 2 лабораторную
inittose/OOAP pull request #3
Opened 2024-04-23 15:03 UTC by inittose

2024-04-26 06:57 UTC, CephalonGL requested changes

2024-04-26 06:57 UTC, CephalonGL commented on Contacts/Contacts/Model/Services/ContactSerializer.cs
>                  MessageBox.Show("Data is corrupted.\nSave files have been cleared.");
Модельные классы не должны ничего знать о классах View. В данном случае, я бы бросил исключение и поймал на том уровне, где происходит взаимодействие с пользователем

2024-04-26 06:57 UTC, CephalonGL commented on Contacts/Contacts/Model/Services/ContactSerializer.cs
>          /// <param name="contact">Экзепляр класса <see cref="Model.Contact"/>.</param>
ЭкзеМпляр

2024-04-26 06:57 UTC, CephalonGL commented on Contacts/Contacts/ViewModel/BoolToVisibilityConverter.cs
> +            return null;
Сколько значение имеет перечисление Visibility? Если два, то до этого return программа никогда не дойдёт. Тогда можно будет его убрать и заменить реализацию метода на
`return Equals(value, Visibility.Visible);`

2024-04-26 06:57 UTC, CephalonGL commented on Contacts/Contacts/ViewModel/InverseBoolConverter.cs
> +            throw new NotSupportedException();
Почему не поддерживается?

2024-04-26 06:57 UTC, CephalonGL commented on Contacts/Contacts/ViewModel/MainVM.cs
> +        public string? Name
Вместо null для строк лучше использовать значение по умолчанию string.Empty, т.к. случайное обращение к неинициализированной области памяти приведёт к выбросу исключения. А если оно не поймается в нужном месте, программа упадёт.

Здесь важно использовать именно null? Если нет, то заменить на string.Empty. Проверить для всех полей и свойств в решении

2024-04-26 06:57 UTC, CephalonGL commented on Contacts/Contacts/ViewModel/MainVM.cs
> +            if (index > 0 && index >= Contacts.Count)
Когда используешь проверку вхождения объекта в диапазон, помещай этот объект по обе стороны от знака && или ||:
1 <= x && x <= 100 читается лучше, чем
x >= 1 && x <= 100

2024-04-27 05:13 UTC, CephalonGL requested changes

2024-04-27 05:13 UTC, CephalonGL commented on Contacts/Contacts/ViewModel/BoolToVisibilityConverter.cs
> +        public object ConvertBack(
1. По названию метода ожидается, что будет выполнена обратная конвертация чего-то одного во что-то другое. Но в реализации метода выполняется только сравнение. Либо исправить реализацию, либо см. пункт 3

2. Аргументы targetType и culture не используются, убрать

3. Если в методе останется только метод Equals, то избавится от этого метода целиком и использовать везде метод Equals напрямую

2024-04-27 09:54 UTC, Nikita-Isaichenko requested changes

2024-04-27 09:54 UTC, Nikita-Isaichenko commented on Contacts/Contacts/Model/Services/ContactSerializer.cs
> +                return Deserialize() ?? new ObservableCollection<Contact>();
В одну строчку

2024-05-04 08:11 UTC, inittose commented on Contacts/Contacts/ViewModel/InverseBoolConverter.cs
> +            throw new NotSupportedException();
Данный метод не должен поддерживаться, так как `InverseBoolConverter` служит для инверсии булевых значений и хватит одного метода `Convert`. Метод `ConvertBack`, в свою очередь, нельзя убрать, т. к. он реализует интерфейс `IValueConverter` и должен находится в классе как заглушка.

2024-05-04 08:21 UTC, inittose commented on Contacts/Contacts/ViewModel/BoolToVisibilityConverter.cs
> +        public object ConvertBack(
Разве не происходит конвертация из `Visibility` в `bool`? По задумке хватит метода `Equals`, чтобы произвести обратную конвертацию.
Аргументы `targetType` и `culture`, насколько я знаю, убрать нельзя, т. к. они используются в описании метода интерфейса [`IValueConverter`](https://learn.microsoft.com/ru-ru/dotnet/api/system.windows.data.ivalueconverter?view=windowsdesktop-8.0).

2024-05-04 09:34 UTC, Nikita-Isaichenko approved these changes

2024-05-06 09:13 UTC, CephalonGL commented on Contacts/Contacts/ViewModel/BoolToVisibilityConverter.cs
> +        public object ConvertBack(
Конвертация происходит, но это решение неправильное с точки зрения архитектуры, потому что Visibility нельзя конвертировать в bool без потери данных, потому что это перечисление, содержащее 3 значения: Visible, Hidden и Collapsed, в то время как bool имеет только 2 состояния

2024-05-07 07:47 UTC, inittose commented on Contacts/Contacts/ViewModel/InverseBoolConverter.cs
> +            throw new NotSupportedException();
Решил удалить конвертеры значений и обойтись дополнительными свойствами в MainVM. Конвертер значений использовал, потому что про них было написано в методичке.

2024-05-07 07:52 UTC, inittose commented on Contacts/Contacts/ViewModel/BoolToVisibilityConverter.cs
> +        public object ConvertBack(
Удалил этот конвертер значений, вместо него создал свойство типом `Visibility` в MainVM. Атрибут [`UIElement.IsVisible`](https://learn.microsoft.com/ru-ru/dotnet/api/system.windows.uielement.isvisible?view=windowsdesktop-8.0) readonly, поэтому было создано свойство `IsApplyButtonVisible`.

2024-05-08 05:25 UTC, merged