#3 feature(sln): Реализовал 3 лабораторную
inittose/OOAP pull request #4
Opened 2024-05-04 11:22 UTC by inittose

2024-05-13 08:49 UTC, CephalonGL requested changes

2024-05-13 08:49 UTC, CephalonGL commented on Contacts/Contacts/ViewModel/MainVM.cs
> +        /// <returns>Вернет <see cref="string.Empty"/>, если валидация прошла успешно.</returns>
А если валидация провалена?

2024-05-13 08:49 UTC, CephalonGL commented on Contacts/Contacts/ViewModel/MainVM.cs
> +        /// Возвращает сообщение ошибки по заданному свойству.
Тут должно быть описано, что метод делает, а не что возвращает. Переместить это это сообщение в блок returns, а в блок summary написать, что делает метод. Например, выполняет валидацию того-то по таким-то правилам

2024-05-13 08:49 UTC, CephalonGL commented on Contacts/Contacts/ViewModel/MainVM.cs
> +        public string this[string propertyName]
Этим синтаксисом ты пытаешься работать с этой VM-кой как с коллекцией каких-то элементов, однако это главная VM, которая не представляет из себя коллекцию. Для использования данного синтаксиса есть какие-то причины?

2024-05-13 08:49 UTC, CephalonGL commented on Contacts/Contacts/ViewModel/MainVM.cs
> +                        catch (ArgumentException ex)
Недопустимое сокращение "ex"

2024-05-13 08:49 UTC, CephalonGL commented on Contacts/Contacts/ViewModel/MainVM.cs
> +                    case nameof(Name):
Содержимое кейсов оборачивается в скобки, кроме случаев, когда записывается в одну строку

2024-05-13 23:22 UTC, Nikita-Isaichenko requested changes

2024-05-13 23:22 UTC, Nikita-Isaichenko commented on Contacts/Contacts/MainWindow.xaml
> +                        Height="25"
Высоту можно вынести в стили для кнопки

2024-05-13 23:22 UTC, Nikita-Isaichenko commented on Contacts/Contacts/Model/Contact.cs
> +        /// Созадет экземпляр класса <see cref="Contact"/>.
Создает*

2024-05-13 23:22 UTC, Nikita-Isaichenko commented on Contacts/Contacts/Model/Contact.cs
> +        /// Созадет экземпляр класса <see cref="Contact"/>.
Создает*

2024-05-19 13:51 UTC, inittose commented on Contacts/Contacts/ViewModel/MainVM.cs
> +        public string this[string propertyName]
Данный синтаксис использовался в качестве реализации интерфейса [IDataErrorInfo](https://learn.microsoft.com/ru-ru/dotnet/api/system.componentmodel.idataerrorinfo?view=net-8.0). Если я реализую IDataErrorInfo в классе Contact, то придется указывать DataContext выбранного элемента в ContactControl, который использует свойства MainVM. У меня не получилось решить эту проблему через DependencyProperty, поэтому реализация интерфейса IDataErrorInfo осталась в MainVM.

2024-05-23 12:42 UTC, Nikita-Isaichenko commented on Contacts/Contacts/Controls/ContactControl.xaml
> +                <TextBox Margin="3, 3, 8, 3"
здесь не сделал для текстбокса

2024-05-23 13:01 UTC, Nikita-Isaichenko requested changes

2024-05-23 13:01 UTC, Nikita-Isaichenko commented on Contacts/Contacts/Controls/ContactControl.xaml
> +                <TextBox Margin="3, 3, 8, 3"
Для текстбокса margin забыл вынести в стили

2024-06-11 07:05 UTC, CephalonGL approved these changes

2024-06-11 07:16 UTC, merged